 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
  name: jenkins-pvc
  namespace: ci-cd
 spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
   #storageClassName: jenkns # Uncomment and specify if needed