apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: applications
spec:
  project: apps
  source:
    path: k8s/ArgoCD/app-of-apps/apps
    repoURL: https://github.com/deividssanches/devops
    targetRevision: development
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: applications
    server: https://192.168.64.3:6443
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
