apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: ci-cd
spec:
  description: Core Argocd
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://192.168.64.3:6443
 # - namespace: ingress-nginx
#    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false