apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-projects
  namespace: ci-cd
spec:
  project: default
  source:
    path: k8s/ArgoCD/app-of-apps/ci
    repoURL: https://github.com/deividssanches/devops
    targetRevision: development
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: ci-cd
    server: https://rancher-desktop.sanches.com:6443
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
---


