apiVersion: argoproj.io/v1alpha1
kind: AApplication
metadata:
  name: jenkins
  namespace: ci-cd
spec:
  project: default
  source:
    repoURL: https://github.com/deividssanches/devops/
    path: k8s/Jenkins/
    targetRevision: development
  destination:
    server: https://192.168.64.3:6443
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
