# postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: projeto-voltar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi